name: pruebas-proyecto

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.2.7
      
    - name: Install dependencies
      run: |
        bundle install --jobs 4 --retry 3

    - name: Set up Database
      run: |
        bin/rails db:create
        bin/rails db:schema:load